server:
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/
#  level:
#     com.imooc: debug